const tour={active:false,paused:false,index:0,timer:null,executed:new Set(),durationMs:7000};
const STEPS=[
{id:'executive',target:'acquisitionDashboard',arTitle:'1. النظرة التنفيذية',enTitle:'1. Executive overview',arBody:'نبدأ بحجم المحفظة وحالة الإثبات الفعلية: جميع القدرات مرئية، لكن حالة التنفيذ منفصلة عن التحقق الإنتاجي.',enBody:'Start with portfolio scale and the real evidence boundary: all capabilities are visible, while demo status remains separate from production verification.'},
{id:'baseline',target:'network',action:'baseline',arTitle:'2. حالة المدينة الأساسية',enTitle:'2. City baseline',arBody:'تُعاد الشبكة إلى الحالة الأساسية وتُوقف الحركة العشوائية أثناء الجولة حتى تبقى المقارنة قابلة للتكرار.',enBody:'The network is reset to baseline and random simulation drift is paused during the tour so the comparison remains repeatable.'},
{id:'incident',target:'incidentBtn',action:'incident',arTitle:'3. إدخال حادث محاكى',enTitle:'3. Simulated incident',arBody:'نضيف حادثاً محاكياً إلى المقطع E09 داخل نموذج الشبكة، ثم نراقب كيف تتغير حالة المخاطر.',enBody:'A simulated incident is injected into demo-network edge E09, then the shared risk state is recalculated.'},
{id:'twin',target:'twinDecisionResult',action:'twin',arTitle:'4. تحديث التوأم الرقمي للمخاطر',enTitle:'4. Refresh the Dynamic Risk Twin',arBody:'التوأم يجمع الحمل والحوادث والإغلاق وQCS في حالة مخاطر واحدة تُستخدم للمسارات والإشارات والطوارئ.',enBody:'The twin fuses load, incidents, closures and QCS into one shared risk state used by routing, signals and emergency planning.'},
{id:'prediction',target:'predictiveOrchestrationPanel',action:'predictive',arTitle:'5. التنبؤ 5–60 دقيقة',enTitle:'5. Predict 5–60 minutes ahead',arBody:'يستخدم التنبؤ الآن نفس الحالة الحية بعد الحادث ويحدد نقاط الخطر الناشئة عبر 5 و15 و30 و60 دقيقة.',enBody:'Prediction now consumes the same live post-incident state and identifies emerging hotspots across 5, 15, 30 and 60 minutes.'},
{id:'plans',target:'predictiveCandidateRows',arTitle:'6. مقارنة خطط التدخل',enTitle:'6. Compare intervention plans',arBody:'تُرتب الخطط المرشحة وفق Robust Score شفاف يجمع الأداء متعدد الآفاق وأسوأ حالة وتكلفة التدخل.',enBody:'Candidate plans are ranked with a transparent robust score combining multi-horizon performance, worst-case outcome and intervention penalty.'},
{id:'explain',target:'explainableOrchestrationPanel',action:'explain',arTitle:'7. تفسير سبب اختيار الخطة',enTitle:'7. Explain why the plan won',arBody:'يقرأ التفسير الآن نفس حالة الشبكة الحية التي استخدمها التوأم والتنبؤ، ثم يفكك الدرجة حسابياً دون ادعاء تفسير سببي.',enBody:'Explainability now reads the same live network state used by the twin and prediction, then decomposes the score arithmetically without claiming causal explanation.'},
{id:'policy',target:'policyRows',arTitle:'8. Policy Gate',enTitle:'8. Policy gate',arBody:'تمر الخطة نفسها عبر حدود تشغيل معلنة. يمكن رفض الخطة الأعلى حسابياً إذا خالفت السياسة، مع بقاء الموافقة البشرية إلزامية.',enBody:'The same plan is screened against explicit operating limits. A numerically superior plan can be rejected by policy, while human approval remains mandatory.'},
{id:'replay',target:'replayRows',arTitle:'9. Scenario Replay',enTitle:'9. Scenario replay',arBody:'نعيد المقارنة زمنياً بين الخطة المختارة وعدم التدخل انطلاقاً من نفس الحالة الحية بعد الحادث.',enBody:'The selected plan is replayed against no-action from the same live post-incident state.'},
{id:'portfolio',target:'acquisitionFeatureExplorer',arTitle:'10. محفظة القدرات الكاملة',enTitle:'10. Complete capability portfolio',arBody:'تنتهي الجولة في Feature Explorer الذي يعرض جميع القدرات الـ123 وحالتها ومصدرها والوحدة التنفيذية المرتبطة بها إن وجدت.',enBody:'The tour ends in Feature Explorer, which exposes all 123 capabilities with status, source group and linked executable module where available.'}
];
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function isArabic(){return document.documentElement.lang!=='en'}
function label(arText,enText){return isArabic()?arText:enText}
function byId(id){return document.getElementById(id)}
function clearTimer(){if(tour.timer){clearTimeout(tour.timer);tour.timer=null}}
function removeHighlight(){document.querySelectorAll('.guided-focus').forEach(el=>el.classList.remove('guided-focus'))}
async function waitForCoreReady(timeoutMs=15000){const start=Date.now();while(Date.now()-start<timeoutMs){if(window.smartTrafficRuntime?.isReady?.()===true&&window.smartTrafficAppReady===true)return true;if(window.smartTrafficAppFailed)throw new Error(`Core runtime failed: ${window.smartTrafficAppFailed}`);await sleep(100)}throw new Error('Core traffic runtime did not become ready in time')}
async function waitForElement(id,timeoutMs=10000){const start=Date.now();while(Date.now()-start<timeoutMs){const el=byId(id);if(el)return el;await sleep(100)}throw new Error(`Required demo control not ready: ${id}`)}
async function waitForCondition(test,timeoutMs=8000){const start=Date.now();while(Date.now()-start<timeoutMs){if(test())return true;await sleep(100)}return false}
async function runAction(action){if(!action||tour.executed.has(action))return true;await waitForCoreReady();const runtime=window.smartTrafficRuntime;let ok=false;if(action==='baseline'){ok=runtime.resetNetwork?.()===true;runtime.setRunning?.(false);ok=ok&&await waitForCondition(()=>runtime.getState?.()?.network!=null,3000)}else if(action==='incident'){ok=runtime.injectIncident?.('E09',false)===true;ok=ok&&await waitForCondition(()=>{const edge=runtime.getState?.()?.network?.edges?.find(item=>item.id==='E09');return Number(edge?.incidentSeverity||0)>0})}else if(action==='twin'){ok=runtime.refreshTwin?.()===true;ok=ok&&await waitForCondition(()=>runtime.getState?.()?.dynamicRiskTwin?.edges?.length>0)}else if(action==='predictive'){ok=Boolean(runtime.runPredictive?.());ok=ok&&await waitForCondition(()=>byId('predictiveCandidateRows')?.children.length>0)}else if(action==='explain'){const button=await waitForElement('explainableBtn');button.click();ok=await waitForCondition(()=>byId('policyRows')?.children.length>0&&byId('replayRows')?.children.length>0,12000)}if(!ok)throw new Error(`Guided demo action did not complete: ${action}`);tour.executed.add(action);return true}
function ensureController(){let controller=byId('guidedDemoController');if(controller)return controller;controller=document.createElement('aside');controller.id='guidedDemoController';controller.className='guided-controller';controller.setAttribute('aria-live','polite');controller.innerHTML=`<div class="guided-head"><div><span id="guidedStepCount">1 / ${STEPS.length}</span><strong id="guidedTitle">Executive Guided Demo</strong></div><button class="guided-close" id="guidedClose" aria-label="Close guided demo">×</button></div><div class="guided-progress"><i id="guidedProgress"></i></div><p id="guidedBody"></p><div class="guided-boundary">SIMULATION · autoApply=false · humanApprovalRequired=true · production_verified=0</div><div class="guided-actions"><button class="btn" id="guidedPrev">السابق</button><button class="btn" id="guidedPause">إيقاف مؤقت</button><button class="btn primary" id="guidedNext">التالي</button></div>`;document.body.appendChild(controller);byId('guidedClose').onclick=endTour;byId('guidedPrev').onclick=()=>void goTo(Math.max(0,tour.index-1),false);byId('guidedNext').onclick=()=>void goTo(Math.min(STEPS.length-1,tour.index+1),true);byId('guidedPause').onclick=togglePause;return controller}
function renderController(step,overrideBody=null){ensureController().classList.add('visible');byId('guidedStepCount').textContent=`${tour.index+1} / ${STEPS.length}`;byId('guidedTitle').textContent=label(step.arTitle,step.enTitle);byId('guidedBody').textContent=overrideBody??label(step.arBody,step.enBody);byId('guidedProgress').style.width=`${((tour.index+1)/STEPS.length)*100}%`;byId('guidedPrev').textContent=label('السابق','Previous');byId('guidedNext').textContent=tour.index===STEPS.length-1?label('إنهاء الجولة','Finish tour'):label('التالي','Next');byId('guidedPause').textContent=tour.paused?label('استئناف تلقائي','Resume auto'):label('إيقاف مؤقت','Pause auto');byId('guidedPrev').disabled=tour.index===0}
function scheduleNext(){clearTimer();if(!tour.active||tour.paused||tour.index>=STEPS.length-1)return;tour.timer=setTimeout(()=>void goTo(tour.index+1,true),tour.durationMs)}
async function goTo(index,execute=true){if(!tour.active)return;clearTimer();removeHighlight();tour.index=index;const step=STEPS[index];try{if(execute&&step.action){renderController(step,label('جاري تشغيل المحرك والتحقق من النتيجة…','Running engine and verifying result…'));await runAction(step.action)}const target=await waitForElement(step.target,10000);target.classList.add('guided-focus');target.scrollIntoView({behavior:'smooth',block:'center'});renderController(step);byId('guidedNext').onclick=index===STEPS.length-1?endTour:()=>void goTo(Math.min(STEPS.length-1,tour.index+1),true);scheduleNext()}catch(error){console.error('Guided demo step failed:',error);tour.paused=true;renderController(step,label(`تعذر إكمال هذه الخطوة: ${error.message}`,`This step could not complete: ${error.message}`))}}
function togglePause(){tour.paused=!tour.paused;renderController(STEPS[tour.index]);scheduleNext()}
async function startTour(){try{await waitForCoreReady();const acqReady=window.smartTrafficAcquisitionReady===true||await waitForCondition(()=>window.smartTrafficAcquisitionReady===true,10000);if(!acqReady)throw new Error('Acquisition presentation layer did not become ready');const gate=byId('acquisitionEntry');if(gate){byId('acqEnter')?.click();const closed=await waitForCondition(()=>!byId('acquisitionEntry'),3000);if(!closed)throw new Error('Entry layer did not close')}tour.active=true;tour.paused=false;tour.index=0;tour.executed.clear();document.body.classList.add('guided-active');await goTo(0,false)}catch(error){console.error('Guided demo could not start:',error);ensureController();tour.active=true;tour.paused=true;renderController(STEPS[0],label(`تعذر بدء الجولة: ${error.message}`,`Could not start guided demo: ${error.message}`))}}
function endTour(){clearTimer();removeHighlight();tour.active=false;tour.paused=false;document.body.classList.remove('guided-active');byId('guidedDemoController')?.classList.remove('visible');byId('acquisitionFeatureExplorer')?.scrollIntoView({behavior:'smooth',block:'start'})}
function addStartButtons(){if(window.smartTrafficAcquisitionReady!==true||window.smartTrafficRuntime?.isReady?.()!==true)return;const gateActions=document.querySelector('.acq-entry-actions');if(gateActions&&!byId('acqGuidedStart')){const button=document.createElement('button');button.className='btn primary acq-enter guided-start';button.id='acqGuidedStart';button.textContent=label('ابدأ الجولة التنفيذية','Start guided demo');button.onclick=()=>void startTour();gateActions.prepend(button)}const dashboardHead=document.querySelector('#acquisitionDashboard .acq-dashboard-head');if(dashboardHead&&!byId('guidedDemoStart')){const button=document.createElement('button');button.className='btn primary guided-start guided-dashboard-start';button.id='guidedDemoStart';button.textContent=label('ابدأ الجولة التنفيذية','Start guided demo');button.onclick=()=>void startTour();dashboardHead.appendChild(button)}}
function refreshLanguage(){const start1=byId('acqGuidedStart');if(start1)start1.textContent=label('ابدأ الجولة التنفيذية','Start guided demo');const start2=byId('guidedDemoStart');if(start2)start2.textContent=label('ابدأ الجولة التنفيذية','Start guided demo');if(tour.active)renderController(STEPS[tour.index])}
window.addEventListener('smart-traffic:acquisition-ready',addStartButtons);window.addEventListener('smart-traffic:ready',addStartButtons);new MutationObserver(()=>{addStartButtons();refreshLanguage()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});addStartButtons();
window.smartTrafficGuidedDemo={start:()=>void startTour(),stop:endTour,next:()=>void goTo(Math.min(STEPS.length-1,tour.index+1),true),previous:()=>void goTo(Math.max(0,tour.index-1),false)};
